import { StyleSheet, Text, View } from 'react-native';

import { Card, EmployeeScreen, Icon, IconBadge, Icons, ListRow } from '@/components/employee/ui';
import { EmployeeColors as C } from '@/constants/employee-theme';
import { Spacing } from '@/constants/theme';
import { formatShortDate } from '@/data/employee-roster';
import { formatCurrency, usePayslips } from '@/data/employee-payslips';

export default function PayslipsScreen() {
  const payslips = usePayslips();

  return (
    <EmployeeScreen title="Payslips">
      {payslips.length > 0 ? (
        <Card>
          {payslips.map((payslip, i) => (
            <ListRow
              key={payslip.id}
              icon={<IconBadge name={Icons.payslip} />}
              title={formatShortDate(payslip.payDate)}
              subtitle={payslip.label}
              right={<Text style={styles.amount}>{formatCurrency(payslip.amount)}</Text>}
              showDivider={i > 0}
            />
          ))}
        </Card>
      ) : (
        <Card style={styles.emptyCard}>
          <IconBadge name={Icons.payslip} />
          <Text style={styles.emptyTitle}>No payslips yet</Text>
          <Text style={styles.emptyBody}>Your payslips will appear here once you&apos;ve been paid.</Text>
        </Card>
      )}

      <View style={styles.infoCard}>
        <Icon name={Icons.sparkles} color={C.primary} size={20} />
        <View style={styles.infoText}>
          <Text style={styles.infoTitle}>Your payslip is generated by AI</Text>
          <Text style={styles.infoBody}>
            Our smart system calculates your pay, taxes, and super accurately so you can always
            trust what you&apos;re paid.
          </Text>
        </View>
      </View>
    </EmployeeScreen>
  );
}

const styles = StyleSheet.create({
  emptyCard: {
    alignItems: 'center',
    gap: Spacing.two,
    paddingVertical: Spacing.five,
    paddingHorizontal: Spacing.four,
  },
  emptyTitle: {
    color: C.text,
    fontSize: 16,
    fontWeight: '700',
  },
  emptyBody: {
    color: C.textSecondary,
    fontSize: 14,
    textAlign: 'center',
  },
  amount: {
    color: C.text,
    fontSize: 16,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  infoCard: {
    flexDirection: 'row',
    gap: Spacing.three - 4,
    padding: Spacing.three,
    borderRadius: 16,
    backgroundColor: C.primarySoft,
    borderWidth: 1,
    borderColor: '#D4E2FF',
  },
  infoText: {
    flex: 1,
    gap: Spacing.one,
  },
  infoTitle: {
    color: C.primary,
    fontSize: 15,
    fontWeight: '700',
  },
  infoBody: {
    color: C.text,
    fontSize: 14,
    lineHeight: 20,
  },
});
